version: "3.8"

services:
  cart:
    container_name: cart
    build: ./cart/
    ports:
      - "8082:8082" # HTTP

  loms:
    container_name: loms
    build: ./loms/
    ports:
      - "8081:8081" # HTTP
      - "50051:50051" # gRPC
