version: "3.8"

services:
  postgres:
    container_name: pg_db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: ["postgres"]
    environment:
      POSTGRES_DB: loms_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust


  cart:
    container_name: cart
    build: ./cart/
    ports:
      - "8082:8082" # HTTP

  loms:
    container_name: loms
    build: ./loms/
    ports:
      - "8081:8081" # HTTP
      - "50051:50051" # gRPC

