FROM golang:1.22.5-alpine as builder

WORKDIR /app

RUN go install github.com/pressly/goose/v3/cmd/goose@v3.22.1
COPY . .

CMD ["goose", "-dir", ".", "postgres", "postgresql://user:password@pg_db:5432/loms_db?sslmode=disable", "up"]