// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package mock

//go:generate minimock -i gitlab.ozon.dev/1mikle1/homework/cart/internal/adapter/product/service.ProductRepository -o product_repository_mock_test.go -n ProductRepositoryMock -p mock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"gitlab.ozon.dev/1mikle1/homework/cart/internal/domain"
)

// ProductRepositoryMock implements mm_product.ProductRepository
type ProductRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetProduct          func(ctx context.Context, sku domain.Sku) (ip1 *domain.Item, err error)
	funcGetProductOrigin    string
	inspectFuncGetProduct   func(ctx context.Context, sku domain.Sku)
	afterGetProductCounter  uint64
	beforeGetProductCounter uint64
	GetProductMock          mProductRepositoryMockGetProduct
}

// NewProductRepositoryMock returns a mock for mm_product.ProductRepository
func NewProductRepositoryMock(t minimock.Tester) *ProductRepositoryMock {
	m := &ProductRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetProductMock = mProductRepositoryMockGetProduct{mock: m}
	m.GetProductMock.callArgs = []*ProductRepositoryMockGetProductParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mProductRepositoryMockGetProduct struct {
	optional           bool
	mock               *ProductRepositoryMock
	defaultExpectation *ProductRepositoryMockGetProductExpectation
	expectations       []*ProductRepositoryMockGetProductExpectation

	callArgs []*ProductRepositoryMockGetProductParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProductRepositoryMockGetProductExpectation specifies expectation struct of the ProductRepository.GetProduct
type ProductRepositoryMockGetProductExpectation struct {
	mock               *ProductRepositoryMock
	params             *ProductRepositoryMockGetProductParams
	paramPtrs          *ProductRepositoryMockGetProductParamPtrs
	expectationOrigins ProductRepositoryMockGetProductExpectationOrigins
	results            *ProductRepositoryMockGetProductResults
	returnOrigin       string
	Counter            uint64
}

// ProductRepositoryMockGetProductParams contains parameters of the ProductRepository.GetProduct
type ProductRepositoryMockGetProductParams struct {
	ctx context.Context
	sku domain.Sku
}

// ProductRepositoryMockGetProductParamPtrs contains pointers to parameters of the ProductRepository.GetProduct
type ProductRepositoryMockGetProductParamPtrs struct {
	ctx *context.Context
	sku *domain.Sku
}

// ProductRepositoryMockGetProductResults contains results of the ProductRepository.GetProduct
type ProductRepositoryMockGetProductResults struct {
	ip1 *domain.Item
	err error
}

// ProductRepositoryMockGetProductOrigins contains origins of expectations of the ProductRepository.GetProduct
type ProductRepositoryMockGetProductExpectationOrigins struct {
	origin    string
	originCtx string
	originSku string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetProduct *mProductRepositoryMockGetProduct) Optional() *mProductRepositoryMockGetProduct {
	mmGetProduct.optional = true
	return mmGetProduct
}

// Expect sets up expected params for ProductRepository.GetProduct
func (mmGetProduct *mProductRepositoryMockGetProduct) Expect(ctx context.Context, sku domain.Sku) *mProductRepositoryMockGetProduct {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductRepositoryMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ProductRepositoryMockGetProductExpectation{}
	}

	if mmGetProduct.defaultExpectation.paramPtrs != nil {
		mmGetProduct.mock.t.Fatalf("ProductRepositoryMock.GetProduct mock is already set by ExpectParams functions")
	}

	mmGetProduct.defaultExpectation.params = &ProductRepositoryMockGetProductParams{ctx, sku}
	mmGetProduct.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetProduct.expectations {
		if minimock.Equal(e.params, mmGetProduct.defaultExpectation.params) {
			mmGetProduct.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetProduct.defaultExpectation.params)
		}
	}

	return mmGetProduct
}

// ExpectCtxParam1 sets up expected param ctx for ProductRepository.GetProduct
func (mmGetProduct *mProductRepositoryMockGetProduct) ExpectCtxParam1(ctx context.Context) *mProductRepositoryMockGetProduct {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductRepositoryMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ProductRepositoryMockGetProductExpectation{}
	}

	if mmGetProduct.defaultExpectation.params != nil {
		mmGetProduct.mock.t.Fatalf("ProductRepositoryMock.GetProduct mock is already set by Expect")
	}

	if mmGetProduct.defaultExpectation.paramPtrs == nil {
		mmGetProduct.defaultExpectation.paramPtrs = &ProductRepositoryMockGetProductParamPtrs{}
	}
	mmGetProduct.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetProduct.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetProduct
}

// ExpectSkuParam2 sets up expected param sku for ProductRepository.GetProduct
func (mmGetProduct *mProductRepositoryMockGetProduct) ExpectSkuParam2(sku domain.Sku) *mProductRepositoryMockGetProduct {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductRepositoryMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ProductRepositoryMockGetProductExpectation{}
	}

	if mmGetProduct.defaultExpectation.params != nil {
		mmGetProduct.mock.t.Fatalf("ProductRepositoryMock.GetProduct mock is already set by Expect")
	}

	if mmGetProduct.defaultExpectation.paramPtrs == nil {
		mmGetProduct.defaultExpectation.paramPtrs = &ProductRepositoryMockGetProductParamPtrs{}
	}
	mmGetProduct.defaultExpectation.paramPtrs.sku = &sku
	mmGetProduct.defaultExpectation.expectationOrigins.originSku = minimock.CallerInfo(1)

	return mmGetProduct
}

// Inspect accepts an inspector function that has same arguments as the ProductRepository.GetProduct
func (mmGetProduct *mProductRepositoryMockGetProduct) Inspect(f func(ctx context.Context, sku domain.Sku)) *mProductRepositoryMockGetProduct {
	if mmGetProduct.mock.inspectFuncGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("Inspect function is already set for ProductRepositoryMock.GetProduct")
	}

	mmGetProduct.mock.inspectFuncGetProduct = f

	return mmGetProduct
}

// Return sets up results that will be returned by ProductRepository.GetProduct
func (mmGetProduct *mProductRepositoryMockGetProduct) Return(ip1 *domain.Item, err error) *ProductRepositoryMock {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductRepositoryMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ProductRepositoryMockGetProductExpectation{mock: mmGetProduct.mock}
	}
	mmGetProduct.defaultExpectation.results = &ProductRepositoryMockGetProductResults{ip1, err}
	mmGetProduct.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetProduct.mock
}

// Set uses given function f to mock the ProductRepository.GetProduct method
func (mmGetProduct *mProductRepositoryMockGetProduct) Set(f func(ctx context.Context, sku domain.Sku) (ip1 *domain.Item, err error)) *ProductRepositoryMock {
	if mmGetProduct.defaultExpectation != nil {
		mmGetProduct.mock.t.Fatalf("Default expectation is already set for the ProductRepository.GetProduct method")
	}

	if len(mmGetProduct.expectations) > 0 {
		mmGetProduct.mock.t.Fatalf("Some expectations are already set for the ProductRepository.GetProduct method")
	}

	mmGetProduct.mock.funcGetProduct = f
	mmGetProduct.mock.funcGetProductOrigin = minimock.CallerInfo(1)
	return mmGetProduct.mock
}

// When sets expectation for the ProductRepository.GetProduct which will trigger the result defined by the following
// Then helper
func (mmGetProduct *mProductRepositoryMockGetProduct) When(ctx context.Context, sku domain.Sku) *ProductRepositoryMockGetProductExpectation {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductRepositoryMock.GetProduct mock is already set by Set")
	}

	expectation := &ProductRepositoryMockGetProductExpectation{
		mock:               mmGetProduct.mock,
		params:             &ProductRepositoryMockGetProductParams{ctx, sku},
		expectationOrigins: ProductRepositoryMockGetProductExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetProduct.expectations = append(mmGetProduct.expectations, expectation)
	return expectation
}

// Then sets up ProductRepository.GetProduct return parameters for the expectation previously defined by the When method
func (e *ProductRepositoryMockGetProductExpectation) Then(ip1 *domain.Item, err error) *ProductRepositoryMock {
	e.results = &ProductRepositoryMockGetProductResults{ip1, err}
	return e.mock
}

// Times sets number of times ProductRepository.GetProduct should be invoked
func (mmGetProduct *mProductRepositoryMockGetProduct) Times(n uint64) *mProductRepositoryMockGetProduct {
	if n == 0 {
		mmGetProduct.mock.t.Fatalf("Times of ProductRepositoryMock.GetProduct mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetProduct.expectedInvocations, n)
	mmGetProduct.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetProduct
}

func (mmGetProduct *mProductRepositoryMockGetProduct) invocationsDone() bool {
	if len(mmGetProduct.expectations) == 0 && mmGetProduct.defaultExpectation == nil && mmGetProduct.mock.funcGetProduct == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetProduct.mock.afterGetProductCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetProduct.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetProduct implements mm_product.ProductRepository
func (mmGetProduct *ProductRepositoryMock) GetProduct(ctx context.Context, sku domain.Sku) (ip1 *domain.Item, err error) {
	mm_atomic.AddUint64(&mmGetProduct.beforeGetProductCounter, 1)
	defer mm_atomic.AddUint64(&mmGetProduct.afterGetProductCounter, 1)

	mmGetProduct.t.Helper()

	if mmGetProduct.inspectFuncGetProduct != nil {
		mmGetProduct.inspectFuncGetProduct(ctx, sku)
	}

	mm_params := ProductRepositoryMockGetProductParams{ctx, sku}

	// Record call args
	mmGetProduct.GetProductMock.mutex.Lock()
	mmGetProduct.GetProductMock.callArgs = append(mmGetProduct.GetProductMock.callArgs, &mm_params)
	mmGetProduct.GetProductMock.mutex.Unlock()

	for _, e := range mmGetProduct.GetProductMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ip1, e.results.err
		}
	}

	if mmGetProduct.GetProductMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetProduct.GetProductMock.defaultExpectation.Counter, 1)
		mm_want := mmGetProduct.GetProductMock.defaultExpectation.params
		mm_want_ptrs := mmGetProduct.GetProductMock.defaultExpectation.paramPtrs

		mm_got := ProductRepositoryMockGetProductParams{ctx, sku}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetProduct.t.Errorf("ProductRepositoryMock.GetProduct got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetProduct.GetProductMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sku != nil && !minimock.Equal(*mm_want_ptrs.sku, mm_got.sku) {
				mmGetProduct.t.Errorf("ProductRepositoryMock.GetProduct got unexpected parameter sku, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetProduct.GetProductMock.defaultExpectation.expectationOrigins.originSku, *mm_want_ptrs.sku, mm_got.sku, minimock.Diff(*mm_want_ptrs.sku, mm_got.sku))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetProduct.t.Errorf("ProductRepositoryMock.GetProduct got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetProduct.GetProductMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetProduct.GetProductMock.defaultExpectation.results
		if mm_results == nil {
			mmGetProduct.t.Fatal("No results are set for the ProductRepositoryMock.GetProduct")
		}
		return (*mm_results).ip1, (*mm_results).err
	}
	if mmGetProduct.funcGetProduct != nil {
		return mmGetProduct.funcGetProduct(ctx, sku)
	}
	mmGetProduct.t.Fatalf("Unexpected call to ProductRepositoryMock.GetProduct. %v %v", ctx, sku)
	return
}

// GetProductAfterCounter returns a count of finished ProductRepositoryMock.GetProduct invocations
func (mmGetProduct *ProductRepositoryMock) GetProductAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProduct.afterGetProductCounter)
}

// GetProductBeforeCounter returns a count of ProductRepositoryMock.GetProduct invocations
func (mmGetProduct *ProductRepositoryMock) GetProductBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProduct.beforeGetProductCounter)
}

// Calls returns a list of arguments used in each call to ProductRepositoryMock.GetProduct.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetProduct *mProductRepositoryMockGetProduct) Calls() []*ProductRepositoryMockGetProductParams {
	mmGetProduct.mutex.RLock()

	argCopy := make([]*ProductRepositoryMockGetProductParams, len(mmGetProduct.callArgs))
	copy(argCopy, mmGetProduct.callArgs)

	mmGetProduct.mutex.RUnlock()

	return argCopy
}

// MinimockGetProductDone returns true if the count of the GetProduct invocations corresponds
// the number of defined expectations
func (m *ProductRepositoryMock) MinimockGetProductDone() bool {
	if m.GetProductMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetProductMock.invocationsDone()
}

// MinimockGetProductInspect logs each unmet expectation
func (m *ProductRepositoryMock) MinimockGetProductInspect() {
	for _, e := range m.GetProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProductRepositoryMock.GetProduct at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetProductCounter := mm_atomic.LoadUint64(&m.afterGetProductCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetProductMock.defaultExpectation != nil && afterGetProductCounter < 1 {
		if m.GetProductMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ProductRepositoryMock.GetProduct at\n%s", m.GetProductMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ProductRepositoryMock.GetProduct at\n%s with params: %#v", m.GetProductMock.defaultExpectation.expectationOrigins.origin, *m.GetProductMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetProduct != nil && afterGetProductCounter < 1 {
		m.t.Errorf("Expected call to ProductRepositoryMock.GetProduct at\n%s", m.funcGetProductOrigin)
	}

	if !m.GetProductMock.invocationsDone() && afterGetProductCounter > 0 {
		m.t.Errorf("Expected %d calls to ProductRepositoryMock.GetProduct at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetProductMock.expectedInvocations), m.GetProductMock.expectedInvocationsOrigin, afterGetProductCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProductRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetProductInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProductRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProductRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetProductDone()
}
