// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddUpdateStock(ctx context.Context, arg *AddUpdateStockParams) error
	GetStock(ctx context.Context, sku int32) (*Stock, error)
	InsertItem(ctx context.Context, arg *InsertItemParams) error
	InsertOrder(ctx context.Context, arg *InsertOrderParams) (int32, error)
	SelectItem(ctx context.Context, orderID int32) ([]*Item, error)
	SelectOrder(ctx context.Context, orderID int32) (*UserOrder, error)
	UpdateOrderStatus(ctx context.Context, arg *UpdateOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
